In [21]:
import numpy as np

## 1.1 Реализовать функцию REF(), приводящую матрицу к ступенчатому виду.

In [22]:
def ref(matrix):
    matrix = matrix.copy()

    # Получаем размер матрицы
    rows, cols = matrix.shape

    # Индекс строки, с которой начинаем приведение
    lead = 0

    for r in range(rows):
        if lead >= cols:
            return matrix
        i = r
        while matrix[i, lead] == 0:
            i += 1
            if i == rows:
                i = r
                lead += 1
                if lead == cols:
                    return matrix
        # Меняем строки местами, если текущая строка не имеет ведущего элемента
        matrix[[i, r]] = matrix[[r, i]]

        # Обнуляем элементы ниже текущей строки в столбце с ведущим элементом
        for i in range(r + 1, rows):
            matrix[i] = matrix[i] ^ (matrix[r] * matrix[i, lead])

        lead += 1

    return matrix

In [23]:
m = np.array(
    [
        [1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
        [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
        [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    ]
)
ref(m)

array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
m

array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0]])

## 1.2. Реализовать функцию RREF(), приводящую матрицу к приведённому ступенчатому виду.

In [25]:
def rref(matrix):
    # Сначала приводим матрицу к ступенчатому виду
    matrix = ref(matrix)

    rows, cols = matrix.shape

    # Проходим сверху вниз и обнуляем элементы выше ведущих элементов
    for r in range(rows - 1, -1, -1):
        lead = np.argmax(matrix[r] != 0)
        if matrix[r, lead] == 1:
            # Обнуляем элементы выше ведущего
            for i in range(r - 1, -1, -1):
                matrix[i] = matrix[i] ^ (matrix[r] * matrix[i, lead])

    # Проверяем, являются ли строки ненулевыми
    non_zero_rows = np.any(matrix != 0, axis=1)
    # Возвращаем только строки, которые содержат хотя бы один ненулевой элемент
    return matrix[non_zero_rows]

In [26]:
rref(m)

array([[1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

## 1.3. Создать класс линейных кодов LinearCode.

In [27]:
class LinearCode:
    pass

### 1.3.1 На основе входной матрицы сформировать порождающую матрицу в ступенчатом виде.

In [28]:
S = np.array(
    [
        [1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
        [1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
        [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    ]
)

S_ref = ref(S)

In [29]:
S_ref

array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

### 1.3.2 Задать n равное числу столбцов и k равное числу строк полученной матрицы (без учёта полностью нулевых строк).

In [30]:
G = np.array(
    [
        [1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
    ]
)

n, k = G.shape
print(f"{n=}\n{k=}")

n=5
k=11


### 1.3.3 Сформировать проверочную матрицу на основе порождающей.

#### Шаг 1. Сформировать матрицу 𝐆∗ в приведённом ступенчатом видена основе порождающей.

In [31]:
G_s = rref(G)
G_s

array([[1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])

#### Шаг 2. Зафиксировать ведущие столбцы lead матрицы 𝐆∗.

In [32]:
def find_lead_cols(matrix):
    leading_columns = []
    rows, cols = matrix.shape

    for r in range(rows):
        # Находим индекс первого ненулевого элемента в строке
        for c in range(cols):
            if matrix[r, c] != 0:
                leading_columns.append(c)
                break  # Переходим к следующей строке после нахождения ведущего столбца

    return sorted(set(leading_columns))

lead_cols = find_lead_cols(G_s)
print(lead_cols)

[0, 3, 4, 6, 8]


#### Шаг 3. Сформировать сокращённую матрицу 𝐗, удалив ведущие столбцы матрицы 𝐆∗.

In [33]:
X = np.delete(G_s, lead_cols, axis=1)
X

array([[0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1]])

#### Шаг 4. Сформировать матрицу 𝐇, поместив в строки, соответствующие позициям ведущих столбцов строки из 𝐗, а в остальные – строки единичной матрицы.

In [34]:
H = np.zeros((X.shape[0] + max(X.shape), X.shape[1]), dtype=int)
ones = np.eye(max(X.shape), dtype=int)

In [35]:
x_ind = 0
ones_ind = 0

for i in range(H.shape[0]):
    if i in lead_cols:
        H[i] = X[x_ind]
        x_ind += 1
    else:
        H[i] = ones[ones_ind]
        ones_ind += 1

In [36]:
H

array([[0, 1, 1, 1, 1, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

# 1.4 Сформировать все кодовые слова длины n двумя способами.

## 1.4.1 Сложить все слова из порождающего множества, оставить неповторяющиеся

In [37]:
from itertools import combinations

def generate_codewords_by_sum(G):
    codewords = []
    for r in range(1, G.shape[0] + 1):
        for subset in combinations(G, r):
            codeword = np.bitwise_xor.reduce(subset) % 2
            codewords.append(tuple(codeword))
    return np.array(list(set(codewords)))

generate_codewords_by_sum(G)

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1, 1, 1, 0, 1,

## 1.4.2 Взять все двоичные слова длины k, умножить каждое на G.

In [38]:
from itertools import product

def generate_codewords_by_multiplication(G):
    k = G.shape[0]

    codewords = []
    for binary_word in product([0, 1], repeat=k):
        codeword = np.dot(binary_word, G) % 2
        codewords.append(tuple(codeword))
    return np.array(list(set(codewords)))

generate_codewords_by_multiplication(G)

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0],
       [1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 1, 0, 0,

### Убедиться, что полученные множества кодовых слов совпадают

In [42]:
def check_codewords_with_H(codewords, H):
    for word in codewords:
        syndrome = np.dot(word, H) % 2
        if np.any(syndrome != 0):
            return False
    return True

codewords = generate_codewords_by_multiplication(G)
is_good = check_codewords_with_H(codewords, H)
print(f"Корретные слова {is_good=}")

Корретные слова is_good=True


### Убедиться, что умножение кодовых слов на проверочную матрицу в результате даёт нулевые вектора

In [ ]:
check_zero_matrix = []
for code in set_code_word_k:
    one_word = np.dot(code, H) % 2
    check_zero_matrix.append(one_word)
check_zero_matrix

# 1.5 Вычислить кодовое расстояние получившегося кода.

In [46]:
def hamming_distance(word1, word2):
    return np.sum(np.array(word1) != np.array(word2))

def get_code_distance(codewords):
    min_distance = np.inf
    for i in range(len(codewords)):
        for j in range(i + 1, len(codewords)):
            dist = hamming_distance(codewords[i], codewords[j])
            if 0 < dist < min_distance:
                min_distance = dist
    return min_distance

In [48]:
d = get_code_distance(codewords)
t = d - 1
print("Result:")
print("d:", d)
print("t:", t)

Result:
d: 2
t: 1


## 1.5.1 Внести в кодовое слово ошибку кратности не более t, умножить полученное слово на H, убедиться в обнаружении ошибки.

In [50]:
def introduce_error(codeword, error_positions):
    erroneous_word = np.array(codeword, dtype=int)
    for pos in error_positions:
        erroneous_word[pos] = (erroneous_word[pos] + 1) % 2  # Инверсия бита
    return erroneous_word

def detect_error_with_H(codeword, H):
    syndrome = np.dot(codeword, H) % 2
    return syndrome

In [68]:
import random

v = random.choice(codewords)
t = 1

error_positions_t = [random.randint(0, v.shape[0])]
v_with_error_t = introduce_error(v, error_positions_t)

# Проверяем обнаружение ошибки
s_t = detect_error_with_H(v_with_error_t, H)
print("Кодовое слово с ошибкой (кратности t):", v_with_error_t)
print("Синдром ошибки (кратность t):", s_t)
print('\n-> '+("Ошибка обнаружена" if np.any(s_t) else "Ошибка не обнаружена"))

Кодовое слово с ошибкой (кратности t): [1 0 1 1 1 1 0 0 0 0 0]
Синдром ошибки (кратность t): [0 0 1 0 0 0]

-> Ошибка обнаружена


## 1.5.2 Найти для некоторого кодового слова ошибку кратности t+1 такую, что при умножении на H ошибка не может быть обнаружена

In [71]:
new_t = t + 1
new_error_positions = [0, 2, 3, 4]

new_v_with_error = introduce_error(v, new_error_positions)

# Проверяем обнаружение ошибки
s_t_plus_1 = detect_error_with_H(new_v_with_error, H)
print("Кодовое слово с ошибкой (кратности t+1):", new_v_with_error)
print("Синдром ошибки (кратность t+1):", s_t_plus_1)
print('\n-> '+("Ошибка обнаружена" if np.any(s_t_plus_1) else "Ошибка не обнаружена"))

Кодовое слово с ошибкой (кратности t+1): [0 0 0 0 0 0 0 0 0 0 0]
Синдром ошибки (кратность t+1): [0 0 0 0 0 0]

-> Ошибка не обнаружена
